services:
  - type: web
    name: arsol-backend
    env: python
    plan: free
    rootDir: solar-landing/backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        value: postgresql://arsoldb_user:7T7xTevl3eub9ldoAG1MMdKtFgt8aCHl@dpg-d62vc4pr0fns73dpss7g-a/arsoldb
      - key: PYTHON_VERSION
        value: 3.13.4