databases:
  - name: arsol-db
    plan: free
    databaseName: arsoldb

services:
  - type: web
    name: arsol-backend
    env: python
    plan: free
    rootDir: solar-landing/backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: arsol-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.13.4